approvedGitRepositories: []

checksumBehavior: throw

compressionLevel: mixed

enableGlobalCache: false

enableHardenedMode: true

enableScripts: true

enableStrictSsl: true

npmMinimalAgeGate: 1440

unsafeHttpWhitelist: []

yarnPath: .yarn/releases/yarn-4.17.1.cjs
