compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@firebase/database@*":
    dependencies:
      "@firebase/app-types": "*"
  "@google-cloud/opentelemetry-cloud-trace-exporter@*":
    dependencies:
      "@opentelemetry/semantic-conventions": "*"
  "@google-cloud/opentelemetry-resource-util@*":
    dependencies:
      "@opentelemetry/api": "*"

yarnPath: .yarn/releases/yarn-4.0.1.cjs
