compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@google-cloud/opentelemetry-cloud-trace-exporter@*":
    dependencies:
      "@opentelemetry/semantic-conventions": "*"
  "@google-cloud/opentelemetry-resource-util@*":
    dependencies:
      "@opentelemetry/api": "*"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
