compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@google-cloud/opentelemetry-cloud-trace-exporter@*":
    dependencies:
      "@opentelemetry/semantic-conventions": "*"
  "@google-cloud/opentelemetry-resource-util@*":
    dependencies:
      "@opentelemetry/api": "*"
  "@inquirer/core@*":
    dependencies:
      "@types/node": "*"

yarnPath: .yarn/releases/yarn-4.5.2.cjs
