apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${KUSTOMIZER}-${IMAGEN}
  annotations:
    run.googleapis.com/ingress: all # O 'internal-and-cloud-load-balancing' si aplica
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
#        autoscaling.knative.dev/minScale: "1"
#        autoscaling.knative.dev/maxScale: "20"
        autoscaling.knative.dev/target: "80"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/${PROJECT_ID}/${KUSTOMIZER}/${IMAGEN}:${VERSION}
          env:
            - name: DATADOG
              value: "false"
            - name: ENTORNO
              value: "${ENTORNO}"
          ports:
            - containerPort: 8080
          startupProbe:
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 30
            httpGet:
              path: /admin/started/
          readinessProbe:
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /admin/ready/
          livenessProbe:
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /admin/live/
          volumeMounts:
            - name: temporal
              mountPath: "/usr/src/app/files/tmp/"
          resources:
            limits:
              cpu: "1"
              memory: "4096Mi"
      volumes:
        - name: temporal
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
