ARG BASE_IMAGE=node:lts-alpine

FROM ${BASE_IMAGE} AS build
ARG DD_GIT_REPOSITORY_URL
ARG DD_GIT_COMMIT_SHA
ARG RUTA
ARG WS
WORKDIR /usr/src/app
RUN mkdir ./.yarn && mkdir ./.yarn/unplugged
COPY ./.yarn/plugins ./.yarn/plugins
COPY ./.yarn/releases ./.yarn/releases
COPY ./.yarnrc* ./
COPY ./${RUTA}/${WS} ./${RUTA}/${WS}
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn workspaces focus --production ${WS}

FROM ${BASE_IMAGE} AS app
ARG DD_GIT_REPOSITORY_URL
ARG DD_GIT_COMMIT_SHA
ARG RUTA
ARG WS
WORKDIR /usr/src/app
ENV DD_GIT_REPOSITORY_URL=${DD_GIT_REPOSITORY_URL}
ENV DD_GIT_COMMIT_SHA=${DD_GIT_COMMIT_SHA}
ENV NODE_ENV=production
RUN mkdir ./.yarn && mkdir ./files && mkdir -p ./${RUTA}/${WS}/.next && mkdir -p ./${RUTA}/${WS}/public
COPY --from=build /usr/src/app/.yarn ./.yarn
COPY --from=build /usr/src/app/.pnp.* ./
COPY --from=build /usr/src/app/.yarnrc* ./
COPY --from=build /usr/src/app/yarn.lock ./
COPY ./package.json ./
COPY ./framework/services-comun/next.config.js ./${RUTA}/${WS}/next.config.base.js
COPY ./framework/services-comun/next.config.deps.js ./${RUTA}/${WS}
COPY ./framework/services-comun/package.json ./framework/services-comun
COPY ./${RUTA}/${WS}/next.config.js ./${RUTA}/${WS}
COPY ./${RUTA}/${WS}/mrpack.json ./${RUTA}/${WS}
COPY ./${RUTA}/${WS}/package.json ./${RUTA}/${WS}
COPY ./${RUTA}/${WS}/.next ./${RUTA}/${WS}/.next
COPY ./${RUTA}/${WS}/public ./${RUTA}/${WS}/public
RUN echo "#!/usr/bin/env bash" > run.sh
RUN echo "[ -n \"\${DD_SERVICE}\" ] && export DD_SERVICE=\"\$(echo \"\${K8S_NAMESPACE:-default}\" | sed 's/meteored/mr/g')/\${DD_SERVICE}\"" >> run.sh
RUN echo "yarn workspace ${WS} run next start -p 8080" >> run.sh
WORKDIR /usr/src/app/${RUTA}/${WS}
RUN ln -s ../../files ./
WORKDIR /usr/src/app

EXPOSE 8080
CMD [ "sh", "run.sh" ]

#USER node
